/* ============================================================
   lesson-content.js — 七章课程的双语词库
   Bilingual word base for all seven chapters
   key 形如 "L2.sec1.h" / "L2.sec1.p1" / "L2.code2.t" ...
   规则：每个 key 必须同时提供 zh 与 en，缺一不可（由 tools/check.mjs 校验）
   ============================================================ */
(function () {
  'use strict';
  if (!window.I18N) return;

  var D = {

  /* ==========================================================
     第 1 章 · 布局是空间的语言
     ========================================================== */
  'L1.title':      { zh: '布局是空间的语言', en: 'Layout Is the Language of Space' },
  'L1.subtitle':   { zh: '案例 0：一个"能跑但难看"的作品集首页',
                     en: 'Case 0: a portfolio homepage that runs but looks wrong' },
  'L1.intro.p':    { zh: '这是贯穿全课程的案例：设计师 Lin 的个人作品集首页。它的 HTML 结构完全合理——语义标签、正确嵌套、内容齐全，但打开一看就是"不对劲"。本章的任务不是马上写 CSS，而是先学会<b>说出哪里不对劲</b>。因为布局能力的第一层，是观察与命名。',
                     en: 'This is the case that runs through the whole course: designer Lin\u2019s portfolio homepage. Its HTML is perfectly reasonable \u2014 semantic tags, correct nesting, complete content \u2014 yet it looks wrong the moment you open it. The task in this chapter is not to write CSS yet, but to learn to <b>say what exactly is wrong</b>. The first layer of layout skill is observation and naming.' },

  'L1.sec1.num':  { zh: '1.1', en: '1.1' },
  'L1.sec1.h':    { zh: '先测量，再动手', en: 'Measure before you touch anything' },
  'L1.sec1.p1':    { zh: '"难看"不是一个可操作的描述。专业的做法是把主观感受翻译成客观量：字号比、对齐线数量、留白比例、横向溢出像素数。这些量都能用 <code>getBoundingClientRect()</code> 从真实 DOM 里读出来。',
                     en: '\u201cUgly\u201d is not an actionable description. The professional move is to translate a subjective impression into objective quantities: type-size ratio, number of alignment edges, whitespace ratio, pixels of horizontal overflow. All of these can be read from the real DOM with <code>getBoundingClientRect()</code>.' },
  'L1.sec1.p2':    { zh: '本页右侧的演示就是干这件事的：同一份 HTML，切换两种 CSS，实时打印测量值。请先玩一遍再往下读。',
                     en: 'The demo beside this text does exactly that: one HTML document, two stylesheets, live measurement printouts. Play with it before reading on.' },
  'L1.sec1.note':  { zh: '<b>核心习惯</b>：不要靠"感觉差不多"来调布局。每一个调整都应该能回答"我在改变哪个量、期望它变成多少"。',
                     en: '<b>Core habit</b>: never tune layout by \u201clooks about right\u201d. Every change should answer \u201cwhich quantity am I changing, and what do I expect it to become?\u201d' },

  'L1.sec2.num':  { zh: '1.2', en: '1.2' },
  'L1.sec2.h':    { zh: '格式塔原则', en: 'Gestalt principles' },
  'L1.sec2.p1':    { zh: '1923 年，Wertheimer 等人提出"整体不等于部分之和"：人眼不是逐像素扫描，而是先把画面切分成若干"组"，再理解组之间的关系。布局的本质工作，就是<b>控制分组</b>。',
                     en: 'In 1923 Wertheimer and colleagues proposed that the whole is not the sum of its parts: the eye does not scan pixel by pixel but first segments a scene into groups, then interprets the relations between them. The essential job of layout is <b>controlling grouping</b>.' },
  'L1.sec2.table': { zh: '与布局直接相关的四条', en: 'The four principles that matter for layout' },
  'L1.sec2.th1':   { zh: '原则', en: 'Principle' },
  'L1.sec2.th2':   { zh: '含义', en: 'Meaning' },
  'L1.sec2.th3':   { zh: '对应的 CSS 手段', en: 'CSS lever' },
  'L1.sec2.r1a':   { zh: '接近性 Proximity', en: 'Proximity' },
  'L1.sec2.r1b':   { zh: '距离近的自动被读成一组', en: 'Things that are close are read as one group' },
  'L1.sec2.r1c':   { zh: '<code>gap</code> / <code>margin</code> 的层级差', en: 'A hierarchy of <code>gap</code> / <code>margin</code> values' },
  'L1.sec2.r2a':   { zh: '相似性 Similarity', en: 'Similarity' },
  'L1.sec2.r2b':   { zh: '长得像的被读成同类', en: 'Things that look alike are read as the same kind' },
  'L1.sec2.r2c':   { zh: '统一的圆角 / 字号 / 颜色令牌', en: 'Shared radius / size / colour tokens' },
  'L1.sec2.r3a':   { zh: '共同区域 Common region', en: 'Common region' },
  'L1.sec2.r3b':   { zh: '被同一个边界围住的被读成一组', en: 'Things inside one boundary are read as a group' },
  'L1.sec2.r3c':   { zh: '<code>border</code> / <code>background</code> / <code>card</code> 容器', en: '<code>border</code> / <code>background</code> / card containers' },
  'L1.sec2.r4a':   { zh: '连续性 Continuity', en: 'Continuity' },
  'L1.sec2.r4b':   { zh: '沿同一方向排列的被读成序列', en: 'Things along one line are read as a sequence' },
  'L1.sec2.r4c':   { zh: '共享对齐轴（<code>grid</code> 列线）', en: 'A shared alignment axis (<code>grid</code> column lines)' },
  'L1.sec2.p2':    { zh: '记住一句可操作的话：<b>组内间距必须明显小于组间间距</b>。经验值是 1 : 2.5 以上。低于这个比例，读者的眼睛就无法判断"标题属于谁"。',
                     en: 'Keep one actionable rule in mind: <b>the spacing inside a group must be clearly smaller than the spacing between groups</b>. A ratio of 1 : 2.5 or more works in practice. Below that, the reader\u2019s eye cannot tell which heading belongs to which paragraph.' },

  'L1.sec3.num':  { zh: '1.3', en: '1.3' },
  'L1.sec3.h':    { zh: '对齐与视觉层级', en: 'Alignment and visual hierarchy' },
  'L1.sec3.p1':    { zh: '对齐的经济学解释：人眼在换行阅读时需要做一次"回归扫描"（return sweep）。左边缘每多一种位置，这次扫描的成本就上升一次。把页面的左边缘收敛到 2–3 条线上，是降低阅读成本最直接的手段。',
                     en: 'An economic reading of alignment: every line break forces the eye to perform a return sweep. Each additional left-edge position makes that sweep more expensive. Reducing a page to two or three left edges is the most direct way to lower reading cost.' },
  'L1.sec3.ul1':   { zh: '只允许有限种左边缘（正文一条、缩进一条）', en: 'Allow only a few left edges (one for body text, one for indents)' },
  'L1.sec3.ul2':   { zh: '居中适合短文本（标题、按钮），不适合长段落', en: 'Centring suits short text (headings, buttons), never long paragraphs' },
  'L1.sec3.ul3':   { zh: '右对齐只用于数字列，方便按位比较', en: 'Right-align digits only, so magnitudes line up' },
  'L1.sec3.p2':    { zh: '视觉层级则是用"差异"表达"重要性"。差异可以来自字号、字重、颜色对比度、留白多少。经验法则是：相邻层级之间至少要有 1.25 倍的差异才看得出来；标题与正文的比值建议 ≥ 2。',
                     en: 'Visual hierarchy expresses importance through difference: size, weight, colour contrast, and the amount of whitespace around an element. The rule of thumb is that adjacent levels need at least a 1.25\u00d7 difference to be perceptible, and a heading-to-body ratio of 2\u00d7 or more is recommended.' },
  'L1.sec3.note':  { zh: '<b>课堂讨论</b>：为什么"所有字都加粗"等于"没有重点"？因为层级靠的是差异，而不是绝对值——当所有元素都在争夺注意力时，注意力无处可去。',
                     en: '<b>Class discussion</b>: why does \u201cbold everything\u201d mean \u201cno emphasis\u201d? Because hierarchy is about difference, not absolute values \u2014 when everything competes for attention, attention has nowhere to go.' },

  'L1.sec4.num':  { zh: '1.4', en: '1.4' },
  'L1.sec4.h':    { zh: '栅格系统', en: 'The grid system' },
  'L1.sec4.p1':    { zh: '栅格（grid system）是把"对齐"制度化的工具：先定义若干等宽的列与固定间距，再把所有元素吸附到列线上。它把"每个组件单独对齐"变成了"整页共享一套坐标"。代表人物 Josef Müller-Brockmann 在《Grid Systems in Graphic Design》(1961) 中系统化了这套方法。',
                     en: 'A grid system institutionalises alignment: define a set of equal columns and fixed gutters, then snap every element to those lines. It replaces \u201ceach component aligns itself\u201d with \u201cthe whole page shares one coordinate system\u201d. Josef M\u00fcller-Brockmann systematised the method in <i>Grid Systems in Graphic Design</i> (1961).' },
  'L1.sec4.p2':    { zh: '在 CSS 里，栅格不再需要"算百分比"：<code>display: grid</code> 配 <code>repeat(12, 1fr)</code> 就是一套 12 列栅格。第 4 章会详细展开。',
                     en: 'In CSS a grid no longer means computing percentages: <code>display: grid</code> with <code>repeat(12, 1fr)</code> is a 12-column grid. Chapter 4 develops this in detail.' },
  'L1.sec4.note':  { zh: '<b>常见误解</b>：栅格不等于"限制创意"。它约束的是元素之间的相对位置关系，创意空间留在"跨几列""如何分组""如何打破栅格做强调"这些决策上。',
                     en: '<b>Common misconception</b>: a grid does not limit creativity. It constrains the relative positions of elements; creative freedom lives in deciding how many columns to span, how to group, and when to break the grid for emphasis.' },

  'L1.code1.t':    { zh: '关键代码 ① 用测量代替感觉', en: 'Key code ① Replace guessing with measurement' },
  'L1.code1.p':    { zh: '下面这个函数把"难看"变成四个数字。它是本课程所有演示的底层工具，建议直接抄进你的调试工具集。',
                     en: 'This function turns \u201cugly\u201d into four numbers. It is the underlying tool of every demo in this course \u2014 copy it into your debugging kit.' },
  'L1.code1.k':    { zh: '<b>要点</b>：<code>getBoundingClientRect()</code> 返回的是<b>相对视口的渲染后尺寸</b>，已经包含 padding/border/transform，比读 CSS 值更接近用户真实所见。测量横向溢出则要用 <code>documentElement.scrollWidth − clientWidth</code>。',
                     en: '<b>Key point</b>: <code>getBoundingClientRect()</code> returns the <b>rendered, viewport-relative box</b>, already including padding, border and transforms \u2014 far closer to what the user sees than reading CSS values. To measure horizontal overflow use <code>documentElement.scrollWidth \u2212 clientWidth</code>.' },

  'L1.code2.t':    { zh: '关键代码 ② 用间距阶梯表达分组', en: 'Key code ② Express grouping with a spacing scale' },
  'L1.code2.p':    { zh: '格式塔接近性落到代码上，就是"只用少数几个间距值，并且让它们的比例固定"。下面是一个 4px 基准、比例约 1.5 的间距阶梯。',
                     en: 'Translating Gestalt proximity into code means using only a few spacing values whose ratios are fixed. Below is a scale on a 4px base with roughly 1.5\u00d7 steps.' },
  'L1.code2.k':    { zh: '<b>要点</b>：把间距写成 CSS 变量，而不是散落的魔法数字。这样"组内 vs 组间"的比例关系一眼可见，也让第 7 章的"密度切换"成为可能。',
                     en: '<b>Key point</b>: write spacing as CSS custom properties rather than scattered magic numbers. The inner-vs-outer ratio then becomes visible at a glance, and it makes the density switch in chapter 7 possible.' },

  'L1.code3.t':    { zh: '关键代码 ③ 用字号比锁定层级', en: 'Key code ③ Lock hierarchy with a type scale' },
  'L1.code3.p':    { zh: '用一个比例（这里取 1.25 的"大三度"）生成整套字号，保证任何两个相邻层级之间的差异都足够被感知。',
                     en: 'Generate the whole type scale from a single ratio (here 1.25, a major third) so that any two adjacent levels differ enough to be perceived.' },
  'L1.code3.k':    { zh: '<b>要点</b>：配合 <code>clamp()</code> 可以让每个层级的字号随视口缩放，但<b>比值保持不变</b>——层级关系不因屏幕尺寸而瓦解。',
                     en: '<b>Key point</b>: combined with <code>clamp()</code> each level can scale with the viewport while <b>the ratios stay constant</b> \u2014 the hierarchy does not fall apart at different screen sizes.' },

  'L1.demo1.hint': { zh: '切换"未处理布局 / 做过布局"，观察右侧对同一份 DOM 的实时测量：字号比、卡片排列、间距、横向溢出。',
                     en: 'Toggle \u201cuntouched / layout applied\u201d and watch the live measurement of the very same DOM: type ratio, card arrangement, gaps, horizontal overflow.' },
  'L1.demo2.hint': { zh: '拖动两个滑块，亲眼看"组内间距 ≥ 组间间距"时分组是如何崩掉的。这是格式塔原则最直观的实验。',
                     en: 'Drag the two sliders and watch grouping collapse when inner spacing reaches outer spacing. This is the most direct experiment for the proximity principle.' },
  'L1.demo3.hint': { zh: '同一批内容，四种对齐策略。右侧会统计"左边缘不同的 x 值个数"——这个数字就是阅读成本的一个代理指标。',
                     en: 'The same content under four alignment strategies. The readout counts distinct left-edge x values \u2014 a proxy for reading cost.' },

  /* ==========================================================
     第 2 章 · 盒模型与文档流
     ========================================================== */
  'L2.title':      { zh: '盒模型与文档流', en: 'Box Model & Normal Flow' },
  'L2.subtitle':   { zh: '案例 1：为什么侧栏总是差 20px',
                     en: 'Case 1: why the sidebar is always 20px off' },
  'L2.intro.p':    { zh: 'Lin 试图做一个"主区 + 侧栏"的两栏布局：<code>.main{width:640px}</code>、<code>.side{width:320px}</code>，加上 <code>gap:24px</code>，容器是 960px。640+320+24 = 984 > 960，于是侧栏被挤到下一行。他以为是自己算错了减法，实际上是<b>盒模型</b>在起作用：他给两个盒子都加了 <code>padding:20px</code>。',
                     en: 'Lin tries a main-plus-sidebar layout: <code>.main{width:640px}</code>, <code>.side{width:320px}</code>, a <code>gap:24px</code>, inside a 960px container. 640+320+24 = 984 &gt; 960, so the sidebar wraps to the next line. He assumes his arithmetic is wrong, but the real cause is the <b>box model</b>: both boxes also have <code>padding:20px</code>.' },

  'L2.sec1.num':  { zh: '2.1', en: '2.1' },
  'L2.sec1.h':    { zh: '盒子由四层构成', en: 'A box has four layers' },
  'L2.sec1.p1':    { zh: 'CSS 把每个元素渲染为一个矩形盒，从内到外依次是 <b>content → padding → border → margin</b>。关键规则是：<code>width</code> 默认只描述 <b>content</b> 那一层（<code>box-sizing: content-box</code>），padding 与 border 会额外向外扩张。',
                     en: 'CSS renders every element as a rectangle composed, inside out, of <b>content \u2192 padding \u2192 border \u2192 margin</b>. The crucial rule: <code>width</code> by default describes only the <b>content</b> layer (<code>box-sizing: content-box</code>), so padding and border expand the box further outward.' },
  'L2.sec1.table': { zh: '两种 box-sizing 的对比（width 都写 320px，padding 20px，border 2px）',
                     en: 'The two box-sizing modes compared (both write width:320px, padding:20px, border:2px)' },
  'L2.sec1.th1':   { zh: 'box-sizing', en: 'Box-sizing' },
  'L2.sec1.th2':   { zh: 'width 的含义', en: 'What width means' },
  'L2.sec1.th3':   { zh: '实际占据宽度', en: 'Space actually occupied' },
  'L2.sec1.th4':   { zh: '直觉', en: 'Intuition' },
  'L2.sec1.r1a':   { zh: '<code>content-box</code>（默认）', en: '<code>content-box</code> (default)' },
  'L2.sec1.r1b':   { zh: '内容区宽度', en: 'The content area' },
  'L2.sec1.r1c':   { zh: '320 + 2×20 + 2×2 = <b>364px</b>', en: '320 + 2\u00d720 + 2\u00d72 = <b>364px</b>' },
  'L2.sec1.r1d':   { zh: '"我写多少就是多少" ❌ 不成立', en: '\u201cwhat I write is what I get\u201d \u274c false' },
  'L2.sec1.r2a':   { zh: '<code>border-box</code>', en: '<code>border-box</code>' },
  'L2.sec1.r2b':   { zh: '边框外沿宽度', en: 'The outer border edge' },
  'L2.sec1.r2c':   { zh: '<b>320px</b>（padding/border 向内挤）', en: '<b>320px</b> (padding/border push inward)' },
  'L2.sec1.r2d':   { zh: '所见即所写 ✓', en: 'What you write is what you see \u2713' },
  'L2.sec1.note':  { zh: '<b>行业惯例</b>：几乎所有现代项目都会加 <code>*, *::before, *::after { box-sizing: border-box; }</code>。这不是风格偏好，而是因为 <code>border-box</code> 让"容器宽度怎么分"这道算术题变得可推理。',
                     en: '<b>Industry convention</b>: nearly every modern project adds <code>*, *::before, *::after { box-sizing: border-box; }</code>. This is not a style preference \u2014 <code>border-box</code> is what makes \u201chow do I divide the container width\u201d a tractable arithmetic problem.' },

  'L2.sec2.num':  { zh: '2.2', en: '2.2' },
  'L2.sec2.h':    { zh: '外边距塌陷', en: 'Margin collapsing' },
  'L2.sec2.p1':    { zh: '相邻的<b>垂直</b>外边距会合并成较大的那一个，而不是相加。这是规范明确规定的行为，不是浏览器的 bug。触发条件：两个块级盒在正常流中垂直相邻、中间没有 padding/border/行内内容隔开。',
                     en: 'Adjacent <b>vertical</b> margins merge into the larger one instead of adding up. This is specified behaviour, not a browser bug. It is triggered when two block-level boxes are vertically adjacent in normal flow with no padding, border or inline content between them.' },
  'L2.sec2.ul':    { zh: '这解释了三类高频困惑：', en: 'It explains three very common confusions:' },
  'L2.sec2.ul1':   { zh: '① "我明明写了 20+30 的间距，怎么只有 30？"', en: '\u2460 \u201cI wrote 20 + 30 of spacing, why is it only 30?\u201d' },
  'L2.sec2.ul2':   { zh: '② "父元素高度怎么变成 0 了？"（子元素的上外边距跑到了父元素外面，即"外边距穿透"）',
                     en: '\u2461 \u201cWhy is the parent height zero?\u201d (the child\u2019s top margin escapes through the parent \u2014 margin collapsing through)' },
  'L2.sec2.ul3':   { zh: '③ "段落间距总是不均匀"（首尾段落的外边距与容器塌陷）',
                     en: '\u2462 \u201cParagraph spacing is always uneven\u201d (first and last margins collapse with the container)' },
  'L2.sec2.p2':    { zh: '解决办法是让"塌陷不成立"：给父元素建立新的格式化上下文（BFC）。现代 CSS 里最干净的做法是 <code>display: flow-root</code>——它只做这一件事，没有其他副作用。历史上人们用 <code>overflow:hidden</code>、<code>float</code>、<code>display:inline-block</code> 来实现，但都会带来别的问题。',
                     en: 'The fix is to make collapsing inapplicable: give the parent a new formatting context (BFC). The cleanest modern way is <code>display: flow-root</code>, which does exactly that and nothing else. Historically people used <code>overflow:hidden</code>, <code>float</code> or <code>display:inline-block</code>, each of which brings its own side effects.' },

  'L2.sec3.num':  { zh: '2.3', en: '2.3' },
  'L2.sec3.h':    { zh: '正常流与显示类型', en: 'Normal flow and display types' },
  'L2.sec3.table': { zh: '三种显示类型的行为差异', en: 'How the three display types behave' },
  'L2.sec3.th1':   { zh: 'display', en: 'Display' },
  'L2.sec3.th2':   { zh: '是否独占一行', en: 'Own line?' },
  'L2.sec3.th3':   { zh: 'width/height', en: 'Width/height' },
  'L2.sec3.th4':   { zh: '垂直 margin', en: 'Vertical margin' },
  'L2.sec3.th5':   { zh: '典型用途', en: 'Typical use' },
  'L2.sec3.r1a':   { zh: '<code>block</code>', en: '<code>block</code>' },
  'L2.sec3.r1b':   { zh: '是', en: 'Yes' },
  'L2.sec3.r1c':   { zh: '生效', en: 'Applies' },
  'L2.sec3.r1d':   { zh: '生效（会塌陷）', en: 'Applies (collapses)' },
  'L2.sec3.r1e':   { zh: '段落、区块容器', en: 'Paragraphs, section containers' },
  'L2.sec3.r2a':   { zh: '<code>inline</code>', en: '<code>inline</code>' },
  'L2.sec3.r2b':   { zh: '否（参与行盒）', en: 'No (joins a line box)' },
  'L2.sec3.r2c':   { zh: '<b>被忽略</b>', en: '<b>Ignored</b>' },
  'L2.sec3.r2d':   { zh: '水平生效、垂直不撑开行', en: 'Horizontal yes, vertical does not grow the line' },
  'L2.sec3.r2e':   { zh: '链接、强调、图标', en: 'Links, emphasis, icons' },
  'L2.sec3.r3a':   { zh: '<code>inline-block</code>', en: '<code>inline-block</code>' },
  'L2.sec3.r3b':   { zh: '否（可并排）', en: 'No (can sit side by side)' },
  'L2.sec3.r3c':   { zh: '生效', en: 'Applies' },
  'L2.sec3.r3d':   { zh: '生效（不塌陷）', en: 'Applies (no collapsing)' },
  'L2.sec3.r3e':   { zh: '标签、按钮、头像', en: 'Tags, buttons, avatars' },
  'L2.sec3.p1':    { zh: '还有一类"完全脱离正常流"的显示类型：<code>float</code> 与 <code>position: absolute/fixed</code>。它们不再占据原有空间，因此父元素计算高度时"看不见"它们——这就是经典的"高度塌陷"。',
                     en: 'A further category leaves normal flow entirely: <code>float</code> and <code>position: absolute/fixed</code>. They no longer occupy their original space, so the parent cannot \u201csee\u201d them when computing its height \u2014 the classic collapsed-height problem.' },
  'L2.sec3.note':  { zh: '<b>为什么还要学 float</b>：虽然不用它做布局了，但"浮动元素不参与父元素高度计算"这一条，仍然是你理解 <code>flow-root</code>、<code>clearfix</code> 以及老代码的关键。',
                     en: '<b>Why still learn float</b>: even though it is no longer a layout tool, \u201cfloats do not contribute to their parent\u2019s height\u201d remains the key to understanding <code>flow-root</code>, <code>clearfix</code> and legacy code.' },

  'L2.code1.t':    { zh: '关键代码 ① 全局 border-box + 侧栏布局的正确算法',
                     en: 'Key code ① Global border-box + the correct sidebar arithmetic' },
  'L2.code1.p':    { zh: '把全局盒模型设成 border-box 之后，"主区 + 侧栏"就不再需要手算 padding：容器宽 − 间距 = 两栏之和，用 <code>1fr</code> 让主区吸收剩余空间。',
                     en: 'With a global border-box, main-plus-sidebar no longer needs hand-computed padding: container width \u2212 gap = the sum of the two columns, and <code>1fr</code> lets the main area absorb the rest.' },
  'L2.code1.k':    { zh: '<b>要点</b>：<code>minmax(0, 1fr)</code> 里的那个 0 很重要。网格/弹性项目的默认最小尺寸是 <code>auto</code>，长内容会把轨道顶宽；显式写 0 才能让它真正收缩。',
                     en: '<b>Key point</b>: the 0 in <code>minmax(0, 1fr)</code> matters. The default minimum size of a grid or flex item is <code>auto</code>, so long content pushes the track wider; writing 0 explicitly is what lets it actually shrink.' },

  'L2.code2.t':    { zh: '关键代码 ② flow-root 阻止外边距塌陷',
                     en: 'Key code ② Stop margin collapsing with flow-root' },
  'L2.code2.p':    { zh: '左边是塌陷时的结果（间隙 = max(20,30) = 30px），右边是建立 BFC 之后（间隙 = 20+30 = 50px）。',
                     en: 'On the left, the collapsed result (gap = max(20,30) = 30px). On the right, after establishing a BFC (gap = 20+30 = 50px).' },
  'L2.code2.k':    { zh: '<b>要点</b>：<code>display: flow-root</code> 建立 BFC 且不改变元素的外部表现（仍是块级、仍占满一行），因此它是修复塌陷的首选。相比之下 <code>overflow:hidden</code> 会裁剪内容并破坏内部 <code>sticky</code>。',
                     en: '<b>Key point</b>: <code>display: flow-root</code> establishes a BFC without changing the element\u2019s outer behaviour (still block-level, still full width), which makes it the first choice for fixing collapsing. <code>overflow:hidden</code>, by contrast, clips content and breaks any <code>sticky</code> inside.' },

  'L2.code3.t':    { zh: '关键代码 ③ 让 overflow-wrap 处理长单词',
                     en: 'Key code ③ Handle long words with overflow-wrap' },
  'L2.code3.p':    { zh: '一个不含空格的长 URL 或长单词，是"横向滚动条"最常见的来源。它不会换行，于是把整个容器顶宽。',
                     en: 'A long URL or word with no spaces is the most common source of a horizontal scrollbar: it cannot wrap, so it widens the whole container.' },
  'L2.code3.k':    { zh: '<b>要点</b>：<code>overflow-wrap: anywhere</code> 允许在必要时从任意位置断行，而 <code>word-break: break-all</code> 会无差别地切断所有单词，破坏可读性。前者是更安全的选择。',
                     en: '<b>Key point</b>: <code>overflow-wrap: anywhere</code> breaks only when necessary, whereas <code>word-break: break-all</code> chops every word indiscriminately. The former is the safer choice.' },

  'L2.demo1.hint': { zh: '拖动 padding / border / margin 滑块，切换 box-sizing，看"实际占据宽度"如何变化。点击"课堂任务"让盒子恰好填满容器。',
                     en: 'Drag the padding / border / margin sliders, switch box-sizing, and watch the occupied width change. Use the classroom task button to make the box exactly fill the container.' },
  'L2.demo2.hint': { zh: '调两个外边距，观察"数学期望"与"浏览器实测"之间何时出现偏差；勾选 flow-root 让它们重新相等。',
                     en: 'Adjust the two margins and watch when the expected value diverges from the measured one; tick flow-root to make them agree again.' },
  'L2.demo3.hint': { zh: '同一个盒子，切到 inline 后无论怎么拖 width/height 都不动了——这是行内格式化上下文最直观的证据。',
                     en: 'The same box: switch to inline and width/height stop responding no matter how you drag \u2014 the most direct evidence of the inline formatting context.' },

  /* ==========================================================
     第 3 章 · Flexbox 一维布局
     ========================================================== */
  'L3.title':      { zh: 'Flexbox 一维布局', en: 'Flexbox: One-Dimensional Layout' },
  'L3.subtitle':   { zh: '案例 2：导航条与卡片列表', en: 'Case 2: the navbar and the card list' },
  'L3.intro.p':    { zh: 'Lin 的导航条是三个 <code>&lt;a&gt;</code>，它们挤在左边；卡片列表三张卡片高度参差不齐，底部的"查看案例"链接高低不齐。用 flexbox 之前需要先想清楚一件事：他现在处理的都是<b>一维</b>问题——一排东西怎么分配宽度、怎么对齐。',
                     en: 'Lin\u2019s navbar is three <code>&lt;a&gt;</code> elements bunched on the left; his three cards have uneven heights and their \u201cview case study\u201d links do not line up. Before reaching for flexbox, notice one thing: every problem here is <b>one-dimensional</b> \u2014 how a row of things divides width and aligns.' },

  'L3.sec1.num':  { zh: '3.1', en: '3.1' },
  'L3.sec1.h':    { zh: '主轴与交叉轴', en: 'Main axis and cross axis' },
  'L3.sec1.p1':    { zh: 'Flex 容器有两条轴：<b>主轴</b>（由 <code>flex-direction</code> 决定）与垂直于它的<b>交叉轴</b>。<code>justify-content</code> 永远作用于主轴，<code>align-items</code> 永远作用于交叉轴。',
                     en: 'A flex container has two axes: the <b>main axis</b> (set by <code>flex-direction</code>) and the <b>cross axis</b> perpendicular to it. <code>justify-content</code> always acts on the main axis and <code>align-items</code> always on the cross axis.' },
  'L3.sec1.p2':    { zh: '这一句话解释了 90% 的"我明明写了 center 却没居中"：一旦把 <code>flex-direction</code> 改成 <code>column</code>，两条轴互换，原来管水平的属性开始管垂直。',
                     en: 'That single sentence explains 90% of \u201cI wrote center and nothing centred\u201d: change <code>flex-direction</code> to <code>column</code> and the axes swap, so the property that used to control horizontal now controls vertical.' },
  'L3.sec1.table': { zh: 'justify-content 的六个取值（主轴方向）', en: 'The six justify-content values (along the main axis)' },
  'L3.sec1.th1':   { zh: '取值', en: 'Value' },
  'L3.sec1.th2':   { zh: '剩余空间怎么分', en: 'How leftover space is distributed' },
  'L3.sec1.th3':   { zh: '常见场景', en: 'Typical use' },
  'L3.sec1.r1a':   { zh: '<code>flex-start</code>（默认）', en: '<code>flex-start</code> (default)' },
  'L3.sec1.r1b':   { zh: '全部堆在起点', en: 'All packed at the start' },
  'L3.sec1.r1c':   { zh: '默认状态', en: 'The default' },
  'L3.sec1.r2a':   { zh: '<code>flex-end</code>', en: '<code>flex-end</code>' },
  'L3.sec1.r2b':   { zh: '全部堆在终点', en: 'All packed at the end' },
  'L3.sec1.r2c':   { zh: '右侧操作按钮组', en: 'A right-hand action group' },
  'L3.sec1.r3a':   { zh: '<code>center</code>', en: '<code>center</code>' },
  'L3.sec1.r3b':   { zh: '整组居中', en: 'The whole group centred' },
  'L3.sec1.r3c':   { zh: '居中标题栏', en: 'A centred title bar' },
  'L3.sec1.r4a':   { zh: '<code>space-between</code>', en: '<code>space-between</code>' },
  'L3.sec1.r4b':   { zh: '首尾贴边，其余等分', en: 'Ends flush, the rest spread evenly' },
  'L3.sec1.r4c':   { zh: '导航条（logo 左、菜单右）', en: 'Navbar (logo left, menu right)' },
  'L3.sec1.r5a':   { zh: '<code>space-around</code>', en: '<code>space-around</code>' },
  'L3.sec1.r5b':   { zh: '每项两侧留半个间隙', en: 'Half a gap on each side of every item' },
  'L3.sec1.r5c':   { zh: '图标工具栏', en: 'Icon toolbars' },
  'L3.sec1.r6a':   { zh: '<code>space-evenly</code>', en: '<code>space-evenly</code>' },
  'L3.sec1.r6b':   { zh: '每项两侧间隙完全相等', en: 'Exactly equal gaps everywhere' },
  'L3.sec1.r6c':   { zh: '需要绝对均匀时', en: 'When absolute evenness is required' },
  'L3.sec1.note':  { zh: '<b>实践建议</b>：<code>gap</code> 出现之后，<code>space-*</code> 的用途大幅收窄。多数"均匀分布"需求其实用 <code>justify-content: flex-start</code> + <code>gap</code> 表达更清楚，因为 gap 描述的是"元素之间的关系"，而 space-between 描述的是"端点与容器的关系"。',
                     en: '<b>Practical advice</b>: since <code>gap</code> arrived, the <code>space-*</code> values have narrowed in use. Most \u201cevenly distributed\u201d requirements are clearer as <code>justify-content: flex-start</code> plus <code>gap</code>, because gap describes the relation between items while space-between describes the relation between the ends and the container.' },

  'L3.sec2.num':  { zh: '3.2', en: '3.2' },
  'L3.sec2.h':    { zh: 'flex 简写的真实语义', en: 'What the flex shorthand really means' },
  'L3.sec2.p1':    { zh: '<code>flex: 1</code> 是 CSS 里最容易"背下来但没理解"的写法之一。它展开为 <code>flex: 1 1 0%</code>，也就是 <b>grow = 1、shrink = 1、basis = 0%</b>。basis 为 0 是关键：所有项目从"零宽度"开始，剩余空间按 grow 比例平分。',
                     en: '<code>flex: 1</code> is one of the most memorised-but-misunderstood shorthands in CSS. It expands to <code>flex: 1 1 0%</code> \u2014 <b>grow = 1, shrink = 1, basis = 0%</b>. The zero basis is the crux: every item starts from zero width, so leftover space is split in proportion to grow.' },
  'L3.sec2.table': { zh: '几个常用写法的真实含义', en: 'What common spellings actually mean' },
  'L3.sec2.th1':   { zh: '写法', en: 'Spelling' },
  'L3.sec2.th2':   { zh: '展开后', en: 'Expands to' },
  'L3.sec2.th3':   { zh: '效果', en: 'Effect' },
  'L3.sec2.r1a':   { zh: '<code>flex: 1</code>', en: '<code>flex: 1</code>' },
  'L3.sec2.r1b':   { zh: '<code>1 1 0%</code>', en: '<code>1 1 0%</code>' },
  'L3.sec2.r1c':   { zh: '严格等宽（忽略内容多少）', en: 'Strictly equal widths (content ignored)' },
  'L3.sec2.r2a':   { zh: '<code>flex: auto</code>', en: '<code>flex: auto</code>' },
  'L3.sec2.r2b':   { zh: '<code>1 1 auto</code>', en: '<code>1 1 auto</code>' },
  'L3.sec2.r2c':   { zh: '按内容比例分配（内容多的更宽）', en: 'Proportional to content (more content, wider)' },
  'L3.sec2.r3a':   { zh: '<code>flex: none</code>', en: '<code>flex: none</code>' },
  'L3.sec2.r3b':   { zh: '<code>0 0 auto</code>', en: '<code>0 0 auto</code>' },
  'L3.sec2.r3c':   { zh: '完全按内容大小，不伸不缩', en: 'Exactly content-sized, neither growing nor shrinking' },
  'L3.sec2.r4a':   { zh: '<code>flex: 2</code>', en: '<code>flex: 2</code>' },
  'L3.sec2.r4b':   { zh: '<code>2 1 0%</code>', en: '<code>2 1 0%</code>' },
  'L3.sec2.r4c':   { zh: '与 <code>flex:1</code> 的兄弟形成 2 : 1', en: 'Forms a 2 : 1 ratio with a <code>flex:1</code> sibling' },
  'L3.sec2.p2':    { zh: '分配公式：<b>最终宽度 = flex-basis + 剩余空间 × (自己的 grow ÷ Σgrow)</b>。当剩余空间为负时，由 <code>flex-shrink × flex-basis</code> 加权吸收。',
                     en: 'The distribution formula: <b>final size = flex-basis + leftover \u00d7 (own grow \u00f7 \u03a3grow)</b>. When leftover space is negative it is absorbed, weighted by <code>flex-shrink \u00d7 flex-basis</code>.' },

  'L3.sec3.num':  { zh: '3.3', en: '3.3' },
  'L3.sec3.h':    { zh: '一维与二维的分界线', en: 'Where one dimension ends and two begin' },
  'L3.sec3.p1':    { zh: '选择 flex 还是 grid，判断标准只有一条：<b>我需要同时控制行和列吗？</b>只控制一行（或一列）内部的分布 → flex；需要让行与列互相对齐 → grid。',
                     en: 'One question decides flex versus grid: <b>do I need to control rows and columns at the same time?</b> Distributing within a single row (or column) \u2192 flex. Needing rows and columns to align with each other \u2192 grid.' },
  'L3.sec3.ul1':   { zh: '导航条、按钮组、卡片内部（图标 + 文字）→ flex', en: 'Navbars, button groups, card internals (icon + text) \u2192 flex' },
  'L3.sec3.ul2':   { zh: '整页骨架、卡片网格、表单对齐 → grid', en: 'Page skeletons, card grids, form alignment \u2192 grid' },
  'L3.sec3.ul3':   { zh: '两者可以嵌套：grid 的每个格子内部用 flex 排版', en: 'They nest: lay out the inside of each grid cell with flex' },
  'L3.sec3.note':  { zh: '<b>常见错误</b>：用 <code>flex-wrap</code> + 百分比宽度去模拟网格。一旦最后一行不足，卡片宽度就与上面几行不一致——因为 flex 是"每行独立分配"，而 grid 是"先定轨道再放元素"。',
                     en: '<b>Common mistake</b>: simulating a grid with <code>flex-wrap</code> plus percentage widths. As soon as the last row is short, its cards no longer match the widths above \u2014 because flex distributes per line, while grid defines tracks first and then places items.' },

  'L3.code1.t':    { zh: '关键代码 ① 导航条：两端对齐 + 垂直居中',
                     en: 'Key code ① Navbar: push apart and centre vertically' },
  'L3.code1.p':    { zh: '这是 flexbox 最有说服力的例子：过去用 float + 负 margin + line-height 才能勉强实现的效果，现在各一行。',
                     en: 'This is flexbox\u2019s most convincing example: what used to need float plus negative margins plus line-height tricks is now one line each.' },
  'L3.code1.k':    { zh: '<b>要点</b>：<code>align-items: center</code> 对齐的是<b>盒子中线</b>；<code>align-items: baseline</code> 对齐的是<b>第一行文字的基线</b>。导航条左右两侧字号不同时，基线对齐往往比中线对齐更"正"。',
                     en: '<b>Key point</b>: <code>align-items: center</code> aligns box centres; <code>align-items: baseline</code> aligns the first line\u2019s baselines. When the two sides of a navbar use different font sizes, baseline alignment often looks more correct than centring.' },

  'L3.code2.t':    { zh: '关键代码 ② 卡片底部对齐：让链接永远贴底',
                     en: 'Key code ② Bottom-aligned cards: keep the link at the bottom' },
  'L3.code2.p':    { zh: '三张卡片描述文字长度不同，导致"查看案例"链接高低不齐。解法是让卡片成为纵向 flex 容器，并给链接 <code>margin-top: auto</code>——它会吃掉所有剩余空间，把链接推到底部。',
                     en: 'Three cards with different description lengths leave the \u201cview case study\u201d links at different heights. The fix is to make each card a vertical flex container and give the link <code>margin-top: auto</code>, which consumes all leftover space and pushes the link to the bottom.' },
  'L3.code2.k':    { zh: '<b>要点</b>：<code>margin: auto</code> 在 flex 容器里具有"吸收剩余空间"的特殊语义，这是普通块布局里没有的能力。同一个技巧也用来做水平居中（<code>margin-inline: auto</code>）。',
                     en: '<b>Key point</b>: inside a flex container <code>margin: auto</code> gains the special ability to absorb leftover space, which plain block layout does not offer. The same trick centres horizontally with <code>margin-inline: auto</code>.' },

  'L3.code3.t':    { zh: '关键代码 ③ flex: 1 与 flex: auto 的差别',
                     en: 'Key code ③ flex: 1 versus flex: auto' },
  'L3.code3.p':    { zh: '把同一组卡片分别写成 <code>flex: 1</code> 和 <code>flex: auto</code>，肉眼可见的差别来自 basis 是 0 还是 auto。',
                     en: 'Write the same card set as <code>flex: 1</code> and then <code>flex: auto</code>: the visible difference comes from whether the basis is 0 or auto.' },
  'L3.code3.k':    { zh: '<b>要点</b>：需要"等宽"就用 <code>flex: 1</code>；需要"内容多的更宽"就用 <code>flex: auto</code>。分不清这两者，就会写出"有的卡片莫名比其他宽"的界面。',
                     en: '<b>Key point</b>: use <code>flex: 1</code> for equal widths and <code>flex: auto</code> when more content should mean more width. Confusing the two produces interfaces where \u201csome cards are mysteriously wider\u201d.' },

  'L3.demo1.hint': { zh: '切换 row / column，观察 justify 与 align 的作用方向如何互换；把 justify 改成 center 再看它是沿哪个方向居中的。',
                     en: 'Switch between row and column and watch how justify and align swap direction; set justify to center and see which way it centres.' },
  'L3.demo2.hint': { zh: '拖动 grow 与 basis，右侧实时给出"剩余空间 ÷ Σgrow"的算式和预测宽度，并与浏览器实测值对照。',
                     en: 'Drag grow and basis: the panel shows the \u201cleftover \u00f7 \u03a3grow\u201d arithmetic and the predicted widths next to the browser\u2019s measured ones.' },
  'L3.demo3.hint': { zh: '导航条实战：切换 justify-content 与 align-items，右侧会测量品牌与菜单的<b>中线偏移</b>，告诉你是否真的视觉居中。',
                     en: 'Navbar in practice: switch justify-content and align-items; the readout measures the <b>centre offset</b> between brand and menu to tell you whether it is really centred.' },

  /* ==========================================================
     第 4 章 · Grid 二维布局
     ========================================================== */
  'L4.title':      { zh: 'Grid 二维布局', en: 'Grid: Two-Dimensional Layout' },
  'L4.subtitle':   { zh: '案例 3：整页骨架与卡片区', en: 'Case 3: the page skeleton and the card area' },
  'L4.intro.p':    { zh: 'Lin 的卡片区用百分比宽度 + float 拼出来：<code>width: 33.33%</code>，再手算 <code>padding-right</code> 来模拟间距。结果窗口一变宽，三列就对不齐了。他真正需要的是一个"先定义列、再往里放东西"的系统——这就是 Grid。',
                     en: 'Lin builds his card area from percentage widths plus float: <code>width: 33.33%</code> with a hand-computed <code>padding-right</code> to fake the gutters. As soon as the window widens, the three columns stop lining up. What he actually needs is a system that defines columns first and then places items into them \u2014 that is Grid.' },

  'L4.sec1.num':  { zh: '4.1', en: '4.1' },
  'L4.sec1.h':    { zh: '轨道、线与网格区域', en: 'Tracks, lines and areas' },
  'L4.sec1.p1':    { zh: 'Grid 把容器切成<b>轨道</b>（track，一行或一列）、由<b>网格线</b>（line）分隔，多条轨道围成<b>网格区域</b>（area）。元素通过三种方式定位：按线号（<code>grid-column: 2 / 4</code>）、按跨度（<code>grid-column: span 2</code>）、或按区域名（<code>grid-area: sidebar</code>）。',
                     en: 'Grid divides a container into <b>tracks</b> (a row or a column) separated by <b>grid lines</b>, and a region bounded by tracks is a <b>grid area</b>. Items are placed three ways: by line numbers (<code>grid-column: 2 / 4</code>), by span (<code>grid-column: span 2</code>), or by area name (<code>grid-area: sidebar</code>).' },
  'L4.sec1.table': { zh: '三种定位方式的可读性对比', en: 'Readability of the three placement styles' },
  'L4.sec1.th1':   { zh: '方式', en: 'Style' },
  'L4.sec1.th2':   { zh: '写法', en: 'Syntax' },
  'L4.sec1.th3':   { zh: '三个月后还能看懂吗', en: 'Still readable in three months?' },
  'L4.sec1.r1a':   { zh: '按线号', en: 'Line numbers' },
  'L4.sec1.r1b':   { zh: '<code>grid-column: 1 / 3</code>', en: '<code>grid-column: 1 / 3</code>' },
  'L4.sec1.r1c':   { zh: '❌ 需要回去数列', en: '\u274c you have to go back and count columns' },
  'L4.sec1.r2a':   { zh: '按跨度', en: 'Span' },
  'L4.sec1.r2b':   { zh: '<code>grid-column: span 2</code>', en: '<code>grid-column: span 2</code>' },
  'L4.sec1.r2c':   { zh: '△ 知道跨几列，不知在哪', en: '\u25b3 knows the span, not the position' },
  'L4.sec1.r3a':   { zh: '区域命名', en: 'Named areas' },
  'L4.sec1.r3b':   { zh: '<code>grid-area: sidebar</code>', en: '<code>grid-area: sidebar</code>' },
  'L4.sec1.r3c':   { zh: '✓ 名字即语义', en: '\u2713 the name is the semantic' },
  'L4.sec1.p2':    { zh: '<code>grid-template-areas</code> 更是把整页骨架写成了一张"ASCII 图"：每个字符串是一行，重复的名字表示跨列或跨行，<code>.</code> 表示空格子。',
                     en: '<code>grid-template-areas</code> goes further and writes the whole page skeleton as an ASCII diagram: each string is a row, a repeated name spans columns or rows, and <code>.</code> marks an empty cell.' },

  'L4.sec2.num':  { zh: '4.2', en: '4.2' },
  'L4.sec2.h':    { zh: 'fr 不是百分比', en: 'Fr is not a percentage' },
  'L4.sec2.p1':    { zh: '这是 Grid 最需要澄清的一点。<code>1fr 2fr 1fr</code> 的语义是：<b>先扣掉所有固定尺寸轨道与 gap，再把剩下的空间按 1 : 2 : 1 分配</b>。而 <code>25% 50% 25%</code> 直接占满容器，gap 会额外溢出。',
                     en: 'This is the point Grid most needs clarified. <code>1fr 2fr 1fr</code> means: <b>subtract every fixed track and the gaps first, then split what remains 1 : 2 : 1</b>. <code>25% 50% 25%</code> instead fills the container outright, so gaps overflow on top.' },
  'L4.sec2.table': { zh: '容器 1000px、gap 20px、三列时的对比', en: 'Container 1000px, gap 20px, three columns' },
  'L4.sec2.th1':   { zh: '写法', en: 'Writing' },
  'L4.sec2.th2':   { zh: '单列宽度', en: 'Column width' },
  'L4.sec2.th3':   { zh: '总占用', en: 'Total used' },
  'L4.sec2.r1a':   { zh: '<code>1fr 2fr 1fr</code>', en: '<code>1fr 2fr 1fr</code>' },
  'L4.sec2.r1b':   { zh: '(1000 − 40) × ¼ = <b>240px</b>', en: '(1000 \u2212 40) \u00d7 \u00bc = <b>240px</b>' },
  'L4.sec2.r1c':   { zh: '1000px ✓ 刚好铺满', en: '1000px \u2713 exactly filled' },
  'L4.sec2.r2a':   { zh: '<code>25% 50% 25%</code>', en: '<code>25% 50% 25%</code>' },
  'L4.sec2.r2b':   { zh: '1000 × ¼ = <b>250px</b>', en: '1000 \u00d7 \u00bc = <b>250px</b>' },
  'L4.sec2.r2c':   { zh: '1040px ✗ 溢出 40px', en: '1040px \u2717 overflows by 40px' },
  'L4.sec2.p2':    { zh: '<code>minmax()</code> 给轨道加上下限与上限：<code>minmax(240px, 1fr)</code> 表示"至少 240px，有剩余就按 fr 长大"。这正是下一节"内在响应式"的基础。',
                     en: '<code>minmax()</code> adds a floor and a ceiling to a track: <code>minmax(240px, 1fr)</code> means \u201cat least 240px, then grow by fr if there is room\u201d. This is the foundation of the intrinsic responsiveness in the next section.' },

  'L4.sec3.num':  { zh: '4.3', en: '4.3' },
  'L4.sec3.h':    { zh: 'auto-fit 与 auto-fill', en: 'Auto-fit versus auto-fill' },
  'L4.sec3.p1':    { zh: '<code>repeat(auto-fit, minmax(240px, 1fr))</code> 让浏览器自己决定"能放几列"：尽可能多地塞入宽度 ≥ 240px 的轨道，再把剩余卡片拉伸填满。<code>auto-fill</code> 与它的差别只在于：<b>空轨道是否被折叠</b>。',
                     en: '<code>repeat(auto-fit, minmax(240px, 1fr))</code> lets the browser decide how many columns fit: it creates as many tracks of at least 240px as possible, then stretches the items to fill the row. The only difference with <code>auto-fill</code> is <b>whether empty tracks are collapsed</b>.' },
  'L4.sec3.table': { zh: '两者在"卡片少、容器宽"时的差异', en: 'How they differ when there are few cards in a wide container' },
  'L4.sec3.th1':   { zh: '关键字', en: 'Keyword' },
  'L4.sec3.th2':   { zh: '空轨道', en: 'Empty tracks' },
  'L4.sec3.th3':   { zh: '卡片行为', en: 'Card behaviour' },
  'L4.sec3.th4':   { zh: '适用场景', en: 'Best for' },
  'L4.sec3.r1a':   { zh: '<code>auto-fit</code>', en: '<code>auto-fit</code>' },
  'L4.sec3.r1b':   { zh: '被折叠', en: 'Collapsed' },
  'L4.sec3.r1c':   { zh: '拉伸填满整行', en: 'Stretch to fill the row' },
  'L4.sec3.r1d':   { zh: '卡片数量不定的列表', en: 'Lists with an unpredictable item count' },
  'L4.sec3.r2a':   { zh: '<code>auto-fill</code>', en: '<code>auto-fill</code>' },
  'L4.sec3.r2b':   { zh: '被保留', en: 'Preserved' },
  'L4.sec3.r2c':   { zh: '保持最小宽度，右侧留白', en: 'Stay at minimum width, leaving space at the right' },
  'L4.sec3.r2d':   { zh: '希望网格结构稳定不变', en: 'When the grid structure must stay stable' },
  'L4.sec3.note':  { zh: '<b>为什么这很重要</b>：媒体查询描述的是"设备有多宽"，而 <code>auto-fit</code> 描述的是"这里能放几列"。后者在组件被放进侧栏、抽屉、模态框时依然正确——这就是"内在响应式"（intrinsic web design）的核心主张。',
                     en: '<b>Why this matters</b>: a media query describes how wide the device is, whereas <code>auto-fit</code> describes how many columns fit <i>here</i>. The latter remains correct when the component is dropped into a sidebar, a drawer or a modal \u2014 the core claim of intrinsic web design.' },

  'L4.code1.t':    { zh: '关键代码 ① 用区域命名写整页骨架',
                     en: 'Key code ① Write the page skeleton with named areas' },
  'L4.code1.p':    { zh: '这几行字符串就是 Lin 的页面结构图。改版时改的是这张图，而不是散落在各处的定位数字。',
                     en: 'These few strings are Lin\u2019s page structure diagram. A redesign edits this diagram rather than position numbers scattered across the file.' },
  'L4.code1.k':    { zh: '<b>要点</b>：区域名相同的相邻格子会自动合并成一个区域，这就是"跨列"的声明方式；不需要为每个元素单独算线号。',
                     en: '<b>Key point</b>: adjacent cells sharing a name merge into one area automatically \u2014 that is how spanning is declared, with no per-element line arithmetic.' },

  'L4.code2.t':    { zh: '关键代码 ② 不写媒体查询的响应式卡片区',
                     en: 'Key code ② A responsive card area without media queries' },
  'L4.code2.p':    { zh: '一行 CSS 取代三到四个断点。注意 <code>minmax(°)= 0</code> 的最小值决定了"什么时候换行"，也就是事实上的断点。',
                     en: 'One line of CSS replaces three or four breakpoints. Note that the minimum inside <code>minmax()</code> decides when the row wraps \u2014 it is a de facto breakpoint.' },
  'L4.code2.k':    { zh: '<b>要点</b>：最小值应该由<b>内容</b>决定（卡片里最长的那行文字需要多宽才不换行），而不是由设备型号决定。这是内在响应式与传统响应式在思维方式上的分水岭。',
                     en: '<b>Key point</b>: the minimum should be derived from <b>content</b> (how wide the longest line in a card must be to avoid wrapping), not from device models. This is the watershed between intrinsic and classic responsive thinking.' },

  'L4.code3.t':    { zh: '关键代码 ③ minmax(0, 1fr) 防止内容顶宽',
                     en: 'Key code ③ minmax(0, 1fr) keeps content from pushing tracks wider' },
  'L4.code3.p':    { zh: '当一个网格项目里含有不可断行的长内容（长 URL、<code>&lt;pre&gt;</code>、宽表格）时，轨道会被顶宽，进而出现横向滚动条。',
                     en: 'When a grid item contains unbreakable long content (a long URL, a <code>&lt;pre&gt;</code> block, a wide table) the track gets pushed wider and a horizontal scrollbar appears.' },
  'L4.code3.k':    { zh: '<b>要点</b>：<code>1fr</code> 的最小值是 <code>auto</code>（即"不小于内容最小宽度"），所以它不保证收缩。写成 <code>minmax(0, 1fr)</code> 才是"可以缩到 0"，再配合内容自身的 <code>overflow</code> 或 <code>overflow-wrap</code> 处理溢出。',
                     en: '<b>Key point</b>: the minimum of <code>1fr</code> is <code>auto</code> (never smaller than the content\u2019s min-content width), so it does not guarantee shrinking. Writing <code>minmax(0, 1fr)</code> means \u201cmay shrink to zero\u201d, paired with <code>overflow</code> or <code>overflow-wrap</code> on the content itself.' },

  'L4.demo1.hint': { zh: '拖动三列的 fr 比例与 gap，右侧实时打印每条轨道的实测像素宽度，验证"先扣 gap 再分配"这条规则。',
                     en: 'Drag the three fr values and the gap; the readout prints each track\u2019s measured pixel width, verifying the \u201csubtract gaps first, then distribute\u201d rule.' },
  'L4.demo2.hint': { zh: '在 auto-fit 与 auto-fill 之间切换，并拖动"容器宽度"模拟窗口变化。注意卡片少的时候两者的差别。',
                     en: 'Switch between auto-fit and auto-fill and drag the container width to simulate resizing. Watch the difference when there are few cards.' },
  'L4.demo3.hint': { zh: '三种页面骨架模板：侧栏式、圣杯式、杂志式。切换时下面是同一套 CSS 的不同 grid-template-areas 写法。',
                     en: 'Three page-skeleton templates: sidebar, holy grail, magazine. Below, the same CSS with different grid-template-areas.' },

  /* ==========================================================
     第 5 章 · 定位、层叠与溢出
     ========================================================== */
  'L5.title':      { zh: '定位、层叠与溢出', en: 'Positioning, Stacking & Overflow' },
  'L5.subtitle':   { zh: '案例 4：吸顶导航、标签与模态框',
                     en: 'Case 4: sticky nav, badges and the modal' },
  'L5.intro.p':    { zh: 'Lin 要给导航条加"吸顶"效果，给卡片加一个右上角"NEW"角标，再做一个覆盖全屏的模态框。三件事都卡住了：<code>sticky</code> 不生效、角标跑到了页面左上角、模态框被内容盖住。这三个问题共享同一个知识背景——<b>定位与层叠</b>。',
                     en: 'Lin wants a sticky navbar, a \u201cNEW\u201d badge in each card\u2019s top-right corner, and a full-screen modal. All three fail: sticky does nothing, the badge runs off to the page corner, and the modal sits behind the content. All three share one body of knowledge \u2014 <b>positioning and stacking</b>.' },

  'L5.sec1.num':  { zh: '5.1', en: '5.1' },
  'L5.sec1.h':    { zh: '五种 position 与各自的包含块', en: 'Five position values and their containing blocks' },
  'L5.sec1.table': { zh: 'position 取值对照', en: 'Position values compared' },
  'L5.sec1.th1':   { zh: '取值', en: 'Value' },
  'L5.sec1.th2':   { zh: '是否脱离文档流', en: 'Out of flow?' },
  'L5.sec1.th3':   { zh: '包含块（top/left 参照谁）', en: 'Containing block (what top/left refers to)' },
  'L5.sec1.th4':   { zh: '典型用途', en: 'Typical use' },
  'L5.sec1.r1a':   { zh: '<code>static</code>（默认）', en: '<code>static</code> (default)' },
  'L5.sec1.r1b':   { zh: '否', en: 'No' },
  'L5.sec1.r1c':   { zh: '不适用', en: 'Not applicable' },
  'L5.sec1.r1d':   { zh: '默认状态', en: 'The default' },
  'L5.sec1.r2a':   { zh: '<code>relative</code>', en: '<code>relative</code>' },
  'L5.sec1.r2b':   { zh: '否（仍占位）', en: 'No (still occupies space)' },
  'L5.sec1.r2c':   { zh: '它自己原来的位置', en: 'Its own original position' },
  'L5.sec1.r2d':   { zh: '微调位置、充当定位祖先', en: 'Nudging, or acting as a positioning ancestor' },
  'L5.sec1.r3a':   { zh: '<code>absolute</code>', en: '<code>absolute</code>' },
  'L5.sec1.r3b':   { zh: '<b>是</b>', en: '<b>Yes</b>' },
  'L5.sec1.r3c':   { zh: '最近的<b>已定位</b>祖先的内边距盒', en: 'The padding box of the nearest <b>positioned</b> ancestor' },
  'L5.sec1.r3d':   { zh: '角标、下拉菜单、覆盖层', en: 'Badges, dropdowns, overlays' },
  'L5.sec1.r4a':   { zh: '<code>fixed</code>', en: '<code>fixed</code>' },
  'L5.sec1.r4b':   { zh: '<b>是</b>', en: '<b>Yes</b>' },
  'L5.sec1.r4c':   { zh: '视口（除非祖先有 transform/filter）', en: 'The viewport (unless an ancestor has transform/filter)' },
  'L5.sec1.r4d':   { zh: '回到顶部按钮、悬浮工具条', en: 'Back-to-top buttons, floating toolbars' },
  'L5.sec1.r5a':   { zh: '<code>sticky</code>', en: '<code>sticky</code>' },
  'L5.sec1.r5b':   { zh: '否（保留占位）', en: 'No (keeps its space)' },
  'L5.sec1.r5c':   { zh: '最近的可滚动祖先', en: 'The nearest scrollable ancestor' },
  'L5.sec1.r5d':   { zh: '吸顶导航、表格表头', en: 'Sticky navbars, table headers' },
  'L5.sec1.note':  { zh: '<b>一句话总结</b>：<code>absolute</code> 找的是"最近的已定位祖先"，而<b>有 <code>transform</code>、<code>filter</code>、<code>will-change</code> 的祖先也算已定位</b>——这是"我的 fixed 元素怎么不固定在视口"的头号原因。',
                     en: '<b>One-line summary</b>: <code>absolute</code> looks for the nearest positioned ancestor, and <b>an ancestor with <code>transform</code>, <code>filter</code> or <code>will-change</code> counts as positioned</b> \u2014 the number-one reason for \u201cwhy is my fixed element not fixed to the viewport\u201d.' },

  'L5.sec2.num':  { zh: '5.2', en: '5.2' },
  'L5.sec2.h':    { zh: 'sticky 的三个前提', en: 'The three preconditions for sticky' },
  'L5.sec2.p1':    { zh: '<code>position: sticky</code> 是"相对定位"与"固定定位"的混合体：在滚动到阈值之前它随正常流移动，越过阈值后粘住，直到父元素边界。它的失效几乎总是下面三条之一：',
                     en: '<code>position: sticky</code> is a hybrid of relative and fixed: it travels with normal flow until it crosses a threshold, then sticks until the parent\u2019s boundary. When it fails it is almost always one of these three:' },
  'L5.sec2.ul1':   { zh: '① <b>没写阈值</b>：只写 <code>position: sticky</code> 而没有 <code>top</code>/<code>bottom</code>，等于没有粘附点。',
                     en: '\u2460 <b>No threshold</b>: <code>position: sticky</code> without <code>top</code>/<code>bottom</code> has no point to stick to.' },
  'L5.sec2.ul2':   { zh: '② <b>祖先有 overflow</b>：任何 <code>overflow: hidden/auto/scroll</code> 的祖先会成为新的滚动容器，把 sticky 限制在它内部。',
                     en: '\u2461 <b>An ancestor with overflow</b>: any <code>overflow: hidden/auto/scroll</code> ancestor becomes the scroll container and confines sticky to it.' },
  'L5.sec2.ul3':   { zh: '③ <b>没有可粘的距离</b>：父元素高度等于 sticky 元素高度时，它无处可粘。',
                     en: '\u2462 <b>No room to stick</b>: when the parent is exactly as tall as the sticky element there is nowhere to travel.' },
  'L5.sec2.note':  { zh: '<b>调试方法</b>：在开发者工具里依次检查该元素的每个祖先，看谁产生了 <code>overflow</code> 非 visible 的滚动容器。用 <code>getComputedStyle()</code> 遍历祖先比肉眼找快得多。',
                     en: '<b>How to debug</b>: walk up the ancestors in DevTools looking for one with a non-visible overflow that creates a scroll container. Iterating with <code>getComputedStyle()</code> is much faster than eyeballing.' },

  'L5.sec3.num':  { zh: '5.3', en: '5.3' },
  'L5.sec3.h':    { zh: '层叠上下文', en: 'Stacking contexts' },
  'L5.sec3.p1':    { zh: '这是 CSS 里最容易被误解的机制：<b><code>z-index</code> 只在同一个层叠上下文内部比较</b>。它不是全局优先级，而是"同一层里的排序号"。',
                     en: 'This is the most misunderstood mechanism in CSS: <b><code>z-index</code> is only compared inside one stacking context</b>. It is not a global priority but a rank within its own layer.' },
  'L5.sec3.p2':    { zh: '下面这些情况都会<b>新建</b>一个层叠上下文——注意它们大多与 z-index 无关：',
                     en: 'Each of the following <b>creates</b> a new stacking context \u2014 note that most have nothing to do with z-index:' },
  'L5.sec3.table': { zh: '常见的层叠上下文触发条件', en: 'Common stacking-context triggers' },
  'L5.sec3.th1':   { zh: '触发条件', en: 'Trigger' },
  'L5.sec3.th2':   { zh: '容易踩的坑', en: 'The trap' },
  'L5.sec3.r1a':   { zh: '<code>position</code> 非 static 且 <code>z-index</code> 非 auto', en: 'Non-static <code>position</code> with non-auto <code>z-index</code>' },
  'L5.sec3.r1b':   { zh: '给容器加 z-index 会把所有子元素"关进"这一层', en: 'Adding z-index to a container locks all children into that layer' },
  'L5.sec3.r2a':   { zh: '<code>opacity &lt; 1</code>', en: '<code>opacity &lt; 1</code>' },
  'L5.sec3.r2b':   { zh: '做一个淡入动画，结果弹层被盖住', en: 'A fade animation makes a popover fall behind' },
  'L5.sec3.r3a':   { zh: '<code>transform</code> / <code>filter</code> / <code>backdrop-filter</code> 非 none', en: 'Non-none <code>transform</code> / <code>filter</code> / <code>backdrop-filter</code>' },
  'L5.sec3.r3b':   { zh: '同时还会成为 fixed 元素的包含块', en: 'Also becomes the containing block for fixed elements' },
  'L5.sec3.r4a':   { zh: '<code>isolation: isolate</code>', en: '<code>isolation: isolate</code>' },
  'L5.sec3.r4b':   { zh: '这是"主动创建、无副作用"的推荐手段', en: 'The recommended way to create one deliberately, with no side effects' },
  'L5.sec3.r5a':   { zh: 'flex / grid 容器的子项且 z-index 非 auto', en: 'A flex/grid item with a non-auto z-index' },
  'L5.sec3.r5b':   { zh: '即使 <code>position: static</code> 也会生效（与直觉相反）', en: 'Applies even with <code>position: static</code> (counter-intuitive)' },

  'L5.code1.t':    { zh: '关键代码 ① 可用的吸顶导航', en: 'Key code ① A sticky navbar that actually works' },
  'L5.code1.p':    { zh: '关键是 <code>z-index</code> 与不透明背景：没有背景的 sticky 导航会让内容从下面透出来，看起来像"没生效"。',
                     en: 'The key is <code>z-index</code> plus an opaque background: a sticky navbar without a background lets content show through and looks like it is not working.' },
  'L5.code1.k':    { zh: '<b>要点</b>：还要检查祖先链上有没有 <code>overflow</code>。如果外层为了裁掉横向滚动条写了 <code>overflow-x: hidden</code>，sticky 就只能在那个容器内活动。',
                     en: '<b>Key point</b>: also check the ancestor chain for <code>overflow</code>. If an outer element uses <code>overflow-x: hidden</code> to kill a horizontal scrollbar, sticky can only travel inside that container.' },

  'L5.code2.t':    { zh: '关键代码 ② 卡片角标：relative + absolute 的组合',
                     en: 'Key code ② Card badge: combining relative and absolute' },
  'L5.code2.p':    { zh: '<code>position: relative</code> 常常"什么都不做"，只为了给子元素提供一个包含块。这是它最重要的用途。',
                     en: '<code>position: relative</code> often does nothing visually; its most important job is to provide a containing block for a child.' },
  'L5.code2.k':    { zh: '<b>要点</b>：父元素加 <code>relative</code> 会带来一个副作用——它同时也是一个层叠上下文候选，如果再加上 <code>z-index</code>，子元素的层叠就被隔离了。只想当包含块时，不要顺手加 z-index。',
                     en: '<b>Key point</b>: adding <code>relative</code> to the parent has a side effect \u2014 it is also a stacking-context candidate, so adding a <code>z-index</code> on top isolates the children\u2019s stacking. When you only need a containing block, do not add z-index out of habit.' },

  'L5.code3.t':    { zh: '关键代码 ③ 模态框的层叠策略',
                     en: 'Key code ③ A stacking strategy for modals' },
  'L5.code3.p':    { zh: '不要靠"把 z-index 写到 99999"来解决问题。正确做法是给页面划分有限的几层，并把每一层的起点写进设计令牌。',
                     en: 'Do not solve stacking by writing z-index: 99999. The right approach is to define a small number of layers and record each layer\u2019s starting value in design tokens.' },
  'L5.code3.k':    { zh: '<b>要点</b>：模态框最好渲染在 <code>&lt;body&gt;</code> 的直接子级（或用 <code>&lt;dialog&gt;</code>），这样它就不会落进任何祖先的层叠上下文。这也是很多 UI 库把弹层挂到 body 的原因。',
                     en: '<b>Key point</b>: a modal is best rendered as a direct child of <code>&lt;body&gt;</code> (or as a <code>&lt;dialog&gt;</code>) so it cannot fall inside any ancestor\u2019s stacking context. This is why many UI libraries portal overlays to the body.' },

  'L5.demo1.hint': { zh: '在框内滚动，切换五种 position，观察 target 与 Box B/C 的相对位置，以及包含块如何随父级 position 改变。',
                     en: 'Scroll inside the box, switch through the five position values, and watch how the target moves relative to Box B/C and how the containing block changes with the parent.' },
  'L5.demo2.hint': { zh: '给父级加 z-index，看子元素那个 9999 是如何"失效"的。右侧用 elementFromPoint 实测到底谁在上层。',
                     en: 'Give the parent a z-index and watch the child\u2019s 9999 lose its power. The readout uses elementFromPoint to measure who is really on top.' },
  'L5.demo3.hint': { zh: '四种 overflow 取值 + 可调的溢出内容。切到 hidden 时注意提示：它会同时破坏内部的 sticky。',
                     en: 'Four overflow values with adjustable overflow content. When you switch to hidden, note the warning: it also breaks any sticky inside.' },

  /* ==========================================================
     第 6 章 · 响应式与流式思维
     ========================================================== */
  'L6.title':      { zh: '响应式与流式思维', en: 'Responsive & Fluid Thinking' },
  'L6.subtitle':   { zh: '案例 5：从 320px 到 1440px', en: 'Case 5: from 320px to 1440px' },
  'L6.intro.p':    { zh: 'Lin 的页面在 1440px 上很好看，在手机上却出现横向滚动、按钮被地址栏遮住、标题挤成两行。<code>@media (max-width: 768px)</code> 加了一条又一条，但总有一段宽度"两边都不像"。本章要换一种思路：不去描述设备，而是描述内容。',
                     en: 'Lin\u2019s page looks good at 1440px, but on a phone it scrolls sideways, the button hides under the address bar and the title wraps onto two cramped lines. He keeps adding <code>@media (max-width: 768px)</code> rules, yet some widths look wrong either way. This chapter changes the approach: stop describing devices and start describing content.' },

  'L6.sec1.num':  { zh: '6.1', en: '6.1' },
  'L6.sec1.h':    { zh: '断点是症状，不是病因', en: 'Breakpoints are symptoms, not causes' },
  'L6.sec1.p1':    { zh: '传统响应式流程是"先写桌面版，再为窄屏打补丁"。它的问题在于：断点位置是拍脑袋定的，断点之间形成"死区"，而组件被复用到大小的容器里时完全不适用。',
                     en: 'The classic responsive workflow is \u201cwrite desktop first, then patch narrow screens\u201d. Its problems: breakpoint positions are guessed, the ranges between them become dead zones, and the rules stop applying as soon as the component is reused in a different container size.' },
  'L6.sec1.p2':    { zh: '更好的做法是先问：<b>这个布局在什么宽度下会"不够用"？</b>把断点定在那个由内容决定的临界点上，而不是定在某个流行设备的宽度上。',
                     en: 'A better approach: first ask <b>at what width does this layout stop working?</b> Put the breakpoint at that content-determined threshold rather than at the width of a popular device.' },
  'L6.sec1.note':  { zh: '<b>可操作的判据</b>：把浏览器窗口慢慢拖窄，直到某一刻你觉得"这里难看了"——那一刻的宽度就是断点。这个动作叫"内容优先的断点设计"。',
                     en: '<b>An actionable test</b>: drag the window narrower until the moment it starts to look bad \u2014 that width is your breakpoint. This practice is called content-first breakpoint design.' },

  'L6.sec2.num':  { zh: '6.2', en: '6.2' },
  'L6.sec2.h':    { zh: '流式 vs 阶梯式', en: 'Fluid versus stepped' },
  'L6.sec2.p1':    { zh: '媒体查询产生的是<b>阶梯函数</b>：字号在断点处从 20px 跳到 44px，中间没有过渡。而 <code>clamp()</code> 产生的是<b>连续函数</b>：字号随视口线性变化，并在一头一尾被截断。',
                     en: 'A media query produces a <b>step function</b>: the font size jumps from 20px to 44px with nothing in between. <code>clamp()</code> produces a <b>continuous function</b>: the size varies linearly with the viewport and is clamped at both ends.' },
  'L6.sec2.table': { zh: '两种策略的对比', en: 'The two strategies compared' },
  'L6.sec2.th1':   { zh: '维度', en: 'Aspect' },
  'L6.sec2.th2':   { zh: '媒体查询', en: 'Media queries' },
  'L6.sec2.th3':   { zh: 'clamp() 流式', en: 'Clamp() fluid' },
  'L6.sec2.r1a':   { zh: '函数形状', en: 'Function shape' },
  'L6.sec2.r1b':   { zh: '阶梯（不连续）', en: 'Step (discontinuous)' },
  'L6.sec2.r1c':   { zh: '线性（连续）', en: 'Linear (continuous)' },
  'L6.sec2.r2a':   { zh: '断点之间', en: 'Between breakpoints' },
  'L6.sec2.r2b':   { zh: '死区，容易出现尴尬尺寸', en: 'A dead zone with awkward sizes' },
  'L6.sec2.r2c':   { zh: '始终处于合理区间', en: 'Always inside a sensible range' },
  'L6.sec2.r3a':   { zh: '代码量', en: 'Code volume' },
  'L6.sec2.r3b':   { zh: '每个断点一条规则', en: 'One rule per breakpoint' },
  'L6.sec2.r3c':   { zh: '一行', en: 'One line' },
  'L6.sec2.r4a':   { zh: '可访问性', en: 'Accessibility' },
  'L6.sec2.r4b':   { zh: '缩放时可能不跟随', en: 'May not follow browser zoom' },
  'L6.sec2.r4c':   { zh: '需要确认用户缩放仍可用', en: 'Still verify that user zoom works' },
  'L6.sec2.p2':    { zh: '注意 <code>clamp()</code> 不等于"随视口无限缩放"。它的三个参数分别是<b>下限、首选值、上限</b>，两端都被截断——这恰好保证了极小屏不会小到读不清、超宽屏不会大到失控。',
                     en: 'Note that <code>clamp()</code> does not mean unbounded scaling. Its three arguments are <b>minimum, preferred, maximum</b>, and both ends are clamped \u2014 which guarantees text stays readable on tiny screens and does not explode on ultrawide ones.' },

  'L6.sec3.num':  { zh: '6.3', en: '6.3' },
  'L6.sec3.h':    { zh: '容器查询与内在响应式', en: 'Container queries and intrinsic design' },
  'L6.sec3.p1':    { zh: '媒体查询问的是"浏览器窗口多宽"，容器查询问的是"<b>我这个组件现在多宽</b>"。当同一个卡片组件同时出现在宽主区和窄侧栏时，只有后者能给出正确答案。',
                     en: 'A media query asks how wide the browser window is; a container query asks <b>how wide this component currently is</b>. When the same card component appears both in a wide main column and a narrow sidebar, only the latter can answer correctly.' },
  'L6.sec3.table': { zh: '响应式判断依据的演进', en: 'The evolution of the responsive trigger' },
  'L6.sec3.th1':   { zh: '年代', en: 'Era' },
  'L6.sec3.th2':   { zh: '判断依据', en: 'Trigger' },
  'L6.sec3.th3':   { zh: '局限', en: 'Limitation' },
  'L6.sec3.r1a':   { zh: '2010 前后', en: 'Around 2010' },
  'L6.sec3.r1b':   { zh: '视口宽度（媒体查询）', en: 'Viewport width (media queries)' },
  'L6.sec3.r1c':   { zh: '不知道组件所处的容器', en: 'Blind to the component\u2019s container' },
  'L6.sec3.r2a':   { zh: '2018 前后', en: 'Around 2018' },
  'L6.sec3.r2b':   { zh: '可用空间（<code>auto-fit</code> / <code>minmax</code>）', en: 'Available space (<code>auto-fit</code> / <code>minmax</code>)' },
  'L6.sec3.r2c':   { zh: '只能控制列数，不能改变组件内部', en: 'Controls column count, not the component internals' },
  'L6.sec3.r3a':   { zh: '2023 起', en: 'Since 2023' },
  'L6.sec3.r3b':   { zh: '容器尺寸（<code>@container</code>）', en: 'Container size (<code>@container</code>)' },
  'L6.sec3.r3c':   { zh: '需要显式声明 <code>container-type</code>', en: 'Requires an explicit <code>container-type</code>' },
  'L6.sec3.note':  { zh: '<b>三者不互斥</b>：整页骨架用媒体查询（或 <code>auto-fit</code>），组件内部用容器查询，是最常见的组合。',
                     en: '<b>They are not mutually exclusive</b>: the most common combination is media queries (or <code>auto-fit</code>) for the page skeleton and container queries for component internals.' },

  'L6.code1.t':    { zh: '关键代码 ① clamp() 流式字号', en: 'Key code ① Fluid type with clamp()' },
  'L6.code1.p':    { zh: '把"在 360px 时用 20px、在 1100px 时用 44px"这句设计语言，直接翻译成一个表达式。',
                     en: 'Translate the design sentence \u201c20px at 360px wide, 44px at 1100px wide\u201d directly into a single expression.' },
  'L6.code1.k':    { zh: '<b>要点</b>：首选值里的 <code>vw</code> 部分用 <code>calc()</code> 表达斜率，<code>clamp()</code> 负责两端截断。切记<b>不要</b>只写 <code>vw</code>——那样在小屏上会小到无法阅读。',
                     en: '<b>Key point</b>: the <code>vw</code> term inside the preferred value expresses the slope via <code>calc()</code>, and <code>clamp()</code> clamps both ends. Never use bare <code>vw</code> \u2014 on small screens it becomes unreadably small.' },

  'L6.code2.t':    { zh: '关键代码 ② 容器查询', en: 'Key code ② Container queries' },
  'L6.code2.p':    { zh: '先在<b>父元素</b>上声明 <code>container-type: inline-size</code>，再在<b>子元素</b>上用 <code>@container</code> 查询。顺序不能反。',
                     en: 'Declare <code>container-type: inline-size</code> on the <b>parent</b>, then query with <code>@container</code> against the <b>child</b>. The order cannot be reversed.' },
  'L6.code2.k':    { zh: '<b>要点</b>：<code>container-type: inline-size</code> 会让该元素在<b>行内方向</b>上成为查询容器，代价是它在行内方向上的尺寸不再由内容决定（<code>width: auto</code> 会变成占满可用宽度）。',
                     en: '<b>Key point</b>: <code>container-type: inline-size</code> makes the element a query container along the <b>inline axis</b>; the cost is that its inline size is no longer content-driven (<code>width: auto</code> becomes fill-available).' },

  'L6.code3.t':    { zh: '关键代码 ③ 移动端 100dvh 与安全区',
                     en: 'Key code ③ Mobile 100dvh and safe areas' },
  'L6.code3.p':    { zh: '<code>100vh</code> 在移动浏览器上取的是"最大视口高度"，地址栏显示时会把底部内容遮住。<code>dvh</code>（dynamic viewport height）会随浏览器 UI 动态变化。',
                     en: 'On mobile browsers <code>100vh</code> measures the largest viewport height, so the address bar covers the bottom of the content. <code>dvh</code> (dynamic viewport height) reacts to browser UI changes.' },
  'L6.code3.k':    { zh: '<b>要点</b>：配合 <code>env(safe-area-inset-bottom)</code> 可以避开 iPhone 的底部横条。这两个属性能一次性解决"按钮点不到"这类最影响可用性的问题。',
                     en: '<b>Key point</b>: pair it with <code>env(safe-area-inset-bottom)</code> to clear the iPhone home indicator. Together these two solve \u201cthe button cannot be tapped\u201d, one of the most usability-damaging bugs.' },

  'L6.demo1.hint': { zh: '拖动"模拟视口"，在媒体查询模式与内在响应式模式之间对比：前者在断点处突变，后者连续变化。',
                     en: 'Drag the simulated viewport and compare media-query mode with intrinsic mode: the former jumps at the breakpoint, the latter changes continuously.' },
  'L6.demo2.hint': { zh: '拖动 min/max 两个滑块，右侧实时显示浏览器计算出的字号，并标出它是否已经触顶或触底。',
                     en: 'Drag min and max; the readout shows the browser\u2019s computed font size and whether it has already hit the floor or the ceiling.' },
  'L6.demo3.hint': { zh: '左右两个宽度不同的容器里放着同一个卡片组件。切到 @media 模式，看窄侧栏里的卡片如何被"错误地"横排。',
                     en: 'The same card component sits in two containers of different widths. Switch to @media mode and watch the card in the narrow sidebar get laid out horizontally \u2014 incorrectly.' },

  /* ==========================================================
     第 7 章 · 综合实战
     ========================================================== */
  'L7.title':      { zh: '综合实战：交付级布局', en: 'Capstone: A Shippable Layout' },
  'L7.subtitle':   { zh: '案例 6：从"能跑"到"能交付"', en: 'Case 6: from \u201cit runs\u201d to \u201cshippable\u201d' },
  'L7.intro.p':    { zh: '前六章分别解决了 Lin 的一个具体问题。这一章要做两件事：把最终版案例完整实现出来（可切换密度与主题），以及把"布局能力"沉淀成一份可复用的自检清单。',
                     en: 'The previous six chapters each solved one concrete problem for Lin. This chapter does two things: implements the final version of the case (with switchable density and theme), and distils layout skill into a reusable self-check list.' },

  'L7.sec1.num':  { zh: '7.1', en: '7.1' },
  'L7.sec1.h':    { zh: '十个真实翻车点', en: 'Ten real-world pitfalls' },
  'L7.sec1.p1':    { zh: '下面十类问题占了真实项目里布局 bug 的绝大多数。它们的共同点是：<b>都不是语法错误</b>，浏览器不会报错，页面只是安静地长得不对。',
                     en: 'The ten categories below account for the vast majority of layout bugs in real projects. What they share: <b>none is a syntax error</b> \u2014 the browser reports nothing and the page is simply quietly wrong.' },
  'L7.sec1.table': { zh: '十个翻车点与对应的修复', en: 'The ten pitfalls and their fixes' },
  'L7.sec1.th1':   { zh: '#', en: '#' },
  'L7.sec1.th2':   { zh: '症状', en: 'Symptom' },
  'L7.sec1.th3':   { zh: '根因', en: 'Root cause' },
  'L7.sec1.th4':   { zh: '修复', en: 'Fix' },
  'L7.sec1.r1a':   { zh: '<b>01</b>', en: '<b>01</b>' },
  'L7.sec1.r1b':   { zh: '内容溢出容器，出现横向滚动条', en: 'Content overflows, horizontal scrollbar appears' },
  'L7.sec1.r1c':   { zh: 'flex/grid 项目默认 <code>min-width: auto</code>', en: 'Flex/grid items default to <code>min-width: auto</code>' },
  'L7.sec1.r1d':   { zh: '<code>min-width: 0</code> 或 <code>minmax(0, 1fr)</code>', en: '<code>min-width: 0</code> or <code>minmax(0, 1fr)</code>' },
  'L7.sec1.r2a':   { zh: '<b>02</b>', en: '<b>02</b>' },
  'L7.sec1.r2b':   { zh: '图片把布局撑破', en: 'An image blows up the layout' },
  'L7.sec1.r2c':   { zh: '固有尺寸大于容器且无上限', en: 'Intrinsic size exceeds the container with no ceiling' },
  'L7.sec1.r2d':   { zh: '<code>max-width: 100%; height: auto</code>', en: '<code>max-width: 100%; height: auto</code>' },
  'L7.sec1.r3a':   { zh: '<b>03</b>', en: '<b>03</b>' },
  'L7.sec1.r3b':   { zh: '移动端底部按钮被地址栏遮住', en: 'Bottom button hidden by the mobile address bar' },
  'L7.sec1.r3c':   { zh: '<code>100vh</code> 取的是最大视口', en: '<code>100vh</code> measures the largest viewport' },
  'L7.sec1.r3d':   { zh: '<code>100dvh</code> + <code>env(safe-area-inset-*)</code>', en: '<code>100dvh</code> + <code>env(safe-area-inset-*)</code>' },
  'L7.sec1.r4a':   { zh: '<b>04</b>', en: '<b>04</b>' },
  'L7.sec1.r4b':   { zh: '居中在内容变化后偏了', en: 'Centring breaks when the content changes' },
  'L7.sec1.r4c':   { zh: '用负 margin 手算居中', en: 'Hand-computed negative-margin centring' },
  'L7.sec1.r4d':   { zh: '<code>place-items: center</code> / <code>place-content: center</code>', en: '<code>place-items: center</code> / <code>place-content: center</code>' },
  'L7.sec1.r5a':   { zh: '<b>05</b>', en: '<b>05</b>' },
  'L7.sec1.r5b':   { zh: '父元素高度塌陷为 0', en: 'Parent height collapses to zero' },
  'L7.sec1.r5c':   { zh: '浮动/绝对定位子元素脱离文档流', en: 'Floated or absolutely positioned children leave the flow' },
  'L7.sec1.r5d':   { zh: '<code>display: flow-root</code>', en: '<code>display: flow-root</code>' },
  'L7.sec1.r6a':   { zh: '<b>06</b>', en: '<b>06</b>' },
  'L7.sec1.r6b':   { zh: 'sticky 完全没反应', en: 'Sticky does nothing at all' },
  'L7.sec1.r6c':   { zh: '没写 top，或祖先有 overflow', en: 'No top value, or an ancestor has overflow' },
  'L7.sec1.r6d':   { zh: '加阈值 + 移除祖先的 overflow', en: 'Add a threshold and remove the ancestor overflow' },
  'L7.sec1.r7a':   { zh: '<b>07</b>', en: '<b>07</b>' },
  'L7.sec1.r7b':   { zh: '<code>z-index: 9999</code> 仍被盖住', en: '<code>z-index: 9999</code> is still covered' },
  'L7.sec1.r7c':   { zh: '父级新建了层叠上下文', en: 'A parent created a stacking context' },
  'L7.sec1.r7d':   { zh: '检查 <code>transform</code>/<code>opacity</code>/<code>z-index</code>，或改用 portal', en: 'Inspect <code>transform</code>/<code>opacity</code>/<code>z-index</code>, or portal the element' },
  'L7.sec1.r8a':   { zh: '<b>08</b>', en: '<b>08</b>' },
  'L7.sec1.r8b':   { zh: '间距总是不等于预期值', en: 'Gaps never equal what you expect' },
  'L7.sec1.r8c':   { zh: '相邻垂直外边距塌陷', en: 'Adjacent vertical margins collapse' },
  'L7.sec1.r8d':   { zh: '改用 <code>gap</code> 统一管理间距', en: 'Manage spacing with <code>gap</code> instead' },
  'L7.sec1.r9a':   { zh: '<b>09</b>', en: '<b>09</b>' },
  'L7.sec1.r9b':   { zh: '长单词/URL 顶破容器', en: 'Long words or URLs break the container' },
  'L7.sec1.r9c':   { zh: '默认不在单词内部断行', en: 'Words do not break by default' },
  'L7.sec1.r9d':   { zh: '<code>overflow-wrap: anywhere</code>', en: '<code>overflow-wrap: anywhere</code>' },
  'L7.sec1.r10a':   { zh: '<b>10</b>', en: '<b>10</b>' },
  'L7.sec1.r10b':  { zh: '键盘 Tab 顺序与视觉顺序不一致', en: 'Tab order does not match visual order' },
  'L7.sec1.r10c':  { zh: '用 <code>order</code> / <code>grid-row</code> 把元素挪了位置', en: 'Elements were moved with <code>order</code> / <code>grid-row</code>' },
  'L7.sec1.r10d':  { zh: '让 DOM 顺序与视觉顺序一致，或用 <code>tabindex</code> 显式修正', en: 'Keep DOM order equal to visual order, or fix explicitly with <code>tabindex</code>' },

  'L7.sec2.num':  { zh: '7.2', en: '7.2' },
  'L7.sec2.h':    { zh: '交付前的八条自检', en: 'Eight pre-flight checks' },
  'L7.sec2.p1':    { zh: '布局质量必须被测量，否则只能依赖"看着还行"。下面八条都可以在浏览器里客观验证，右侧演示同时给出四个宽度的体检结果。',
                     en: 'Layout quality must be measured; otherwise you are left with \u201clooks about right\u201d. All eight items below are objectively verifiable in a browser, and the demo reports them at four widths simultaneously.' },
  'L7.sec2.ol1':   { zh: '任意宽度下都没有横向滚动条', en: 'No horizontal scrollbar at any width' },
  'L7.sec2.ol2':   { zh: '字号随视口平滑变化，没有断崖', en: 'Type scales smoothly with no cliff edges' },
  'L7.sec2.ol3':   { zh: '移动端触控目标不小于 44×44px', en: 'Touch targets are at least 44\u00d744px on mobile' },
  'L7.sec2.ol4':   { zh: '重点内容在首屏可见，不依赖滚动', en: 'Key content is above the fold' },
  'L7.sec2.ol5':   { zh: '页面缩放 200% 后内容仍可用', en: 'The page is still usable at 200% zoom' },
  'L7.sec2.ol6':   { zh: '键盘 Tab 顺序与视觉顺序一致', en: 'Tab order matches visual order' },
  'L7.sec2.ol7':   { zh: '长单词与 URL 有 <code>overflow-wrap</code> 兜底', en: 'Long words and URLs have an <code>overflow-wrap</code> fallback' },
  'L7.sec2.ol8':   { zh: '图片有 <code>max-width:100%</code> 与宽高比占位，避免布局抖动', en: 'Images have <code>max-width:100%</code> and an aspect-ratio placeholder to avoid layout shift' },

  'L7.sec3.num':  { zh: '7.3', en: '7.3' },
  'L7.sec3.h':    { zh: '从布局到设计令牌', en: 'From layout to design tokens' },
  'L7.sec3.p1':    { zh: '最后一步是把设计决策<b>变量化</b>。当"信息密度"变成一组 CSS 变量时，切换紧凑/常规/宽松只需改变量，而不需要重写任何布局规则——这也是设计系统能够存在的前提。',
                     en: 'The last step is to turn design decisions into <b>variables</b>. Once information density is a set of CSS custom properties, switching compact/regular/comfortable means changing variables rather than rewriting layout rules \u2014 the precondition for any design system.' },
  'L7.sec3.note':  { zh: '<b>课程总结</b>：布局不是记住多少个属性，而是建立一个可测量的心智模型——盒子怎么算大小（第 2 章）、一维空间怎么分（第 3 章）、二维空间怎么定轨道（第 4 章）、谁盖住谁（第 5 章）、如何随可用空间自适应（第 6 章），最后用测量验证一切（第 1、7 章）。',
                     en: '<b>Course summary</b>: layout is not about memorising properties but about building a measurable mental model \u2014 how a box is sized (ch.2), how one-dimensional space is divided (ch.3), how two-dimensional tracks are defined (ch.4), what covers what (ch.5), how everything adapts to available space (ch.6), and finally verifying it all by measurement (ch.1 and ch.7).' },

  'L7.code1.t':    { zh: '关键代码 ① 用设计令牌驱动密度切换',
                     en: 'Key code ① Driving density with design tokens' },
  'L7.code1.p':    { zh: '所有间距都从 <code>--pad</code> 与 <code>--gap</code> 派生。切换密度时页面的比例关系保持不变，变的是尺度。',
                     en: 'Every gap derives from <code>--pad</code> and <code>--gap</code>. Switching density preserves the proportional relationships and changes only the scale.' },
  'L7.code1.k':    { zh: '<b>要点</b>：不要在组件里写死 <code>padding: 16px</code>，而要写 <code>padding: var(--pad)</code>。前者让"全局调整"变成几十处修改。',
                     en: '<b>Key point</b>: never hard-code <code>padding: 16px</code> inside a component; write <code>padding: var(--pad)</code>. The former turns a global adjustment into dozens of edits.' },

  'L7.code2.t':    { zh: '关键代码 ② 完整的交付级布局骨架',
                     en: 'Key code ② The complete shipping-grade layout skeleton' },
  'L7.code2.p':    { zh: '把六章的知识合起来，就是下面这几十行。注意每一行都能追溯到前面某一章的理论。',
                     en: 'Combining six chapters of knowledge yields the few dozen lines below. Every line traces back to a theory from an earlier chapter.' },
  'L7.code2.k':    { zh: '<b>要点</b>：<code>grid-template-columns: repeat(12, 1fr)</code> 提供整页栅格；<code>minmax(0, 1fr)</code> 保证不溢出；<code>clamp()</code> 负责流式字号；<code>flow-root</code> 处理包含关系；<code>sticky</code> + <code>z-index</code> 处理吸顶。',
                     en: '<b>Key point</b>: <code>grid-template-columns: repeat(12, 1fr)</code> supplies the page grid; <code>minmax(0, 1fr)</code> prevents overflow; <code>clamp()</code> handles fluid type; <code>flow-root</code> handles containment; <code>sticky</code> plus <code>z-index</code> handles the sticky header.' },

  'L7.code3.t':    { zh: '关键代码 ③ 可复用的一次性测量函数',
                     en: 'Key code ③ A reusable one-shot audit function' },
  'L7.code3.p':    { zh: '把第 1 章的测量思路包装成一个函数，在开发时随时调用，就能在用户之前发现溢出与层级问题。',
                     en: 'Wrap the measurement idea from chapter 1 into a function you can call at any time during development, and you will find overflow and hierarchy problems before your users do.' },
  'L7.code3.k':    { zh: '<b>要点</b>：这段代码可以直接粘进 DevTools Console 运行。好的调试工具不需要复杂，只需要把"感觉"变成"数字"。',
                     en: '<b>Key point</b>: paste this straight into the DevTools console. Good debugging tools need not be complex \u2014 they only need to turn a feeling into a number.' },

  'L7.demo1.hint': { zh: '十个翻车点逐个演示：切换"应用修复"看同一段代码如何从坏变好，也可以自动播放全部十个。',
                     en: 'Ten pitfalls, one at a time: toggle \u201capply the fix\u201d to see the same snippet go from broken to correct, or auto-play all ten.' },
  'L7.demo2.hint': { zh: '四个宽度同时体检：360 / 480 / 768 / 1024px。右侧清单可勾选，得分实时更新。',
                     en: 'Four widths audited at once: 360 / 480 / 768 / 1024px. Tick the list on the right and the score updates live.' },
  'L7.demo3.hint': { zh: '最终版案例：切换紧凑/常规/宽松三种密度与三种主题，观察同一套 CSS 如何产出完全不同的气质。',
                     en: 'The final case: switch between compact/regular/comfortable density and three themes to see one stylesheet produce three very different feels.' },

  /* ==========================================================
     通用：三个 tab 的说明与提示
     ========================================================== */
  'L.demoHint':    { zh: '提示', en: 'Tip' }
  };

  /* 把 L1…L7 的词条注册进 i18n（key 前缀不变，页面直接引用） */
  window.I18N.register(D);

  /* 段落式词条（长文）单独放置，便于将来替换为 markdown */
  window.LESSON_WORDS = D;
})();
